version: '3.5'

services: 
    database:
        image: mysql:8.0
        container_name: tenjin-mysql-80
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD="true"
        volumes:
            - ./db-data:/var/lib/mysql:rw
            - ./database/init:/docker-entrypoint-initdb.d:ro

    tenjin:
        image: gdvfox/tenjin:1.0.1
        container_name: tenjin-app
        ports:
            - '8888:8888'
        depends_on: 
            - database

    swagger-editor:
        image: swaggerapi/swagger-editor
        container_name: tenjin-swagger-editor
        depends_on:
            - tenjin

    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: tenjin-swagger-ui
        volumes:
            - ./swagger/openapi.json:/openapi.json
        environment:
            SWAGGER_JSON: /openapi.json
        depends_on:
            - tenjin

    swagger-nginx:
        image: nginx:mainline-alpine
        container_name: tenjin-nginx
        ports:
            - '443:443'
            - '80:80'
        volumes:
            - ./nginx/ssl:/etc/ssl/gdvfox
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - tenjin
            - swagger-ui
