version: '3.5'

services: 
    database:
        image: mysql:8.0
        container_name: tenjin-mysql-80
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD="true"
        ports:
            - '5706:3306'
        volumes:
            - ./db-data:/var/lib/mysql:rw
            - ./database/init:/docker-entrypoint-initdb.d:ro

    tenjin:
        image: gdvfox/tenjin:1.0.0
        container_name: tenjin-app
        environment:
            - CORS_HOSTS="http://127.0.0.1:8081"
        ports:
            - '8888:8888'
        depends_on: 
            - database

    swagger-editor:
        image: swaggerapi/swagger-editor
        container_name: tenjin-swagger-editor
        ports:
            - '8081:8080'

    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: tenjin-swagger-ui
        ports:
            - '8082:8080'
        volumes:
            - ./swagger/openapi.json:/openapi.json
        environment:
            SWAGGER_JSON: /openapi.json

    swagger-nginx:
        image: nginx:mainline-alpine
        container_name: tenjin-nginx
        ports:
            - '8084:8084'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - tenjin